version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install
  pre_build:
    commands:
      - echo "Configurando variables..."
      - REPO_NAME="erp-demo"
      - REPO_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${REPO_NAME}"
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
      - if [ -z "$BRANCH_NAME" ]; then BRANCH_NAME="dev"; fi
      - echo "Rama detectada:" $BRANCH_NAME
  build:
    commands:
      - echo "Iniciando sesión en ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URL
      - echo "Construyendo imagen..."
      - |
        if [ "$BRANCH_NAME" != "main" ]; then
          docker build -t $REPO_URL:$BRANCH_NAME-latest .
        else
          docker pull $REPO_URL:qa-latest
          docker tag $REPO_URL:qa-latest $REPO_URL:prod-latest
        fi
  post_build:
    commands:
      - echo "Subiendo imagen..."
      - |
        if [ "$BRANCH_NAME" != "main" ]; then
          docker push $REPO_URL:$BRANCH_NAME-latest
        else
          docker push $REPO_URL:prod-latest
        fi
      - echo "Bloque 1 completado exitosamente."